package com.ghzel.expensis.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color

val lightColor = ColorScheme(
    primary = main_color,
    onPrimary =  DarkBlue,
    primaryContainer = Color.White,
    onPrimaryContainer =  TextColor,
    inversePrimary =  DarkBlue,
    secondary=  Color.White,
    onSecondary  =  Color.Black,
    secondaryContainer =  GreyColor,
    onSecondaryContainer =  PinkColor,
    tertiary =  GreyColor,
    onTertiary=  GreyColor,
    tertiaryContainer=  GreyColor,
    onTertiaryContainer=  GreyColor,
    background= Bg_Home_Color,
    onBackground  =TextColor,
    surface = Color.White,
    onSurface =  TextColor,
    surfaceVariant =  DarkBlue,
    onSurfaceVariant =  PinkColor,
    surfaceTint= PinkColor,
    inverseSurface =  DarkBlue,
    inverseOnSurface = Color.White,
    error =  RedErrorLight,
    onError =  RedErrorLight,
    errorContainer =  PinkColor,
    onErrorContainer =  RedErrorLight,
    outline =  RedErrorLight,
    outlineVariant =  RedErrorLight,
    scrim =  main_color,
)



val darkColor = ColorScheme(
    primary = main_color,
    onPrimary =  DarkBlue,
    primaryContainer = DarkBlue,
    onPrimaryContainer =  TextColor,
    inversePrimary =  DarkBlue,
    secondary=  cards_color_dark_mode,
    onSecondary  =  Color.Black,
    secondaryContainer =  GreyColor,
    onSecondaryContainer =  PinkColor,
    tertiary =  GreyColor,
    onTertiary=  GreyColor,
    tertiaryContainer=  GreyColor,
    onTertiaryContainer=  GreyColor,
    background= bg_dark_mode,
    onBackground  =GreyColor,
    surface = Color.Black,
    onSurface =  TextColor,
    surfaceVariant =  DarkBlue,
    onSurfaceVariant =  PinkColor,
    surfaceTint= PinkColor,
    inverseSurface =  DarkBlue,
    inverseOnSurface = Color.White,
    error =  RedErrorLight,
    onError =  RedErrorLight,
    errorContainer =  PinkColor,
    onErrorContainer =  RedErrorLight,
    outline =  RedErrorLight,
    outlineVariant =  RedErrorLight,
    scrim =  main_color,
)